services:
  db:
    image: postgres:16
    container_name: effective-mobile-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: effective-mobile-db
    ports: ["5432:5432"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi_backend
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/effective-mobile-db
    command: >
      sh -c "python create_certs.py &&
            alembic upgrade head &&
            uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./backend:/backend

volumes:
  postgres_data:
