"""unique

Revision ID: 22180e7391d0
Revises: 9a67a8a97f0c
Create Date: 2025-10-25 13:21:59.434323

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "22180e7391d0"
down_revision: Union[str, Sequence[str], None] = "9a67a8a97f0c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("users_is_superuser_key"), "users", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("users_is_superuser_key"),
        "users",
        ["is_superuser"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
