"""permissions

Revision ID: 8efce1066137
Revises: 147b45b182dd
Create Date: 2025-10-25 02:23:25.832790

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8efce1066137"
down_revision: Union[str, Sequence[str], None] = "147b45b182dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("permision_level", sa.Integer(), nullable=False)
    )
    op.create_unique_constraint(None, "user", ["is_superuser"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.drop_column("user", "permision_level")
    # ### end Alembic commands ###
